version: "3.9"
services:
  database:
    build: database
    ports:
      - "5432:5432"

  backend:
    build: backend
    depends_on:
      - database
    ports:
      - "8050:8050"
      
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
